spring:
  profiles:
    active: ${profile}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
        ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE